
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Acceuil ma bibliothèque en ligne</title>
</head>
<body>
<table>
  <tr>
    <td>Nom</td>
    <td>Mode de reliure</td>
    <td>Auteur</td>
    <td>Date</td>
    <td>prix</td>
  </tr>
  <tr>
     <td><?= print_r($books)?></td>
  </tr>
</table>
</body>
</html>
